name: Code verification
on:
  push:
    branches:
      [Refactoring, master]
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Code verification
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:

          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: (.eslintrc.json, .eslintrc.json, .husky/ , .dockerignore, .editorconfig, .gitignore)
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_HTML: false
          VALIDATE_CSS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
